services:
  runner:
    image: ghe-actions-runner
    restart: always
    env_file:
      - ${ENV_FILE}
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
